main = "main.ts"
dev = [
  "proto",
  "run",
  "deno",
  "--",
  "run",
  "--watch",
  "--allow-net",
  "--allow-env",
  "--allow-read",
  "{main}",
]
install = "proto install --yes"
start = [
  "proto",
  "run",
  "deno",
  "--",
  "run",
  "--allow-net",
  "--allow-env",
  "--allow-read",
  "{main}",
]

[build]
install = "proto install --yes"
build = "true"
targets = ["linux-x86_64-glibc", "linux-aarch64-glibc", "linux-x86_64-musl", "linux-aarch64-musl"]
